### ISSUE TITLE
Publish latest PR merge?

### ISSUE THREAD

**Issue by noopkat** [Pinoccio/js-stk500#9]
Hello! :wave: 

Just wondering if the latest changes could please be published to npm? I think it's under @soldair's npm account.

Thanks so much!
Suz :grin:

**Comment by matthijskooijman** [comment]
@soldair, will you pick this one up?

**Comment by soldair** [comment]
yeah ill put it up now =)

**Comment by soldair** [comment]
ok published v1.0.1 
sorry for the wait!

**Comment by noopkat** [comment]
thank you so much, everyone! Happy holidays :heart:
